### ISSUE TITLE
modal - info - Anna

### ISSUE THREAD

**Issue by NalinKane** [NalinKane/Project-1#6]
adding all the information that needs to be included in the modal 
url - website and menu
photos
contact details
table reservations
ratings/reviews
distance to locations

**Comment by Dcox270891** [comment]
While testing if you don't close the modal and look for another restaurant to show more it adds all the information on the bottom of the modal and overflows it

**Comment by Dcox270891** [comment]
also while testing the modal is always appearing at the top of the page which may not always been in the screen

**Comment by NalinKane** [comment]
will be looking at it

**Comment by NalinKane** [comment]
okay so changed the position to "fixed" and upon closing, the data gets wiped and when you click again, it is pulled into the modal again. 

will be working on the overflowing issue
